# Generated by Django 3.2.6 on 2021-11-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wongnork', '0002_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
