# Generated by Django 3.1.2 on 2021-11-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wongnork', '0004_auto_20211105_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='images/')),
                ('detail', models.CharField(max_length=1000000)),
                ('rating', models.FloatField(max_length=5)),
            ],
        ),
    ]
