# Generated by Django 3.1.2 on 2021-11-10 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wongnork', '0005_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100)),
                ('review_description', models.CharField(max_length=500)),
                ('review_rate', models.IntegerField(default=0)),
                ('review_price', models.IntegerField(default=0)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wongnork.restaurant')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
